import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "@/styles/globals.css";
import NavbarSite from "../components/Navbar-site";
import FooterSite from "@/components/Footer-site";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        <NavbarSite />
        {children}
        <FooterSite />
      </body>
    </html>
  );
}
